- name: Set Default Scheme
  run: |
    cd ios
    scheme_list=$(xcodebuild -list -json | tr -d "\n")
    default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
    echo $default | cat >default
    echo Using default scheme: $default
- name: Build
  env:
    scheme: ${{ 'default' }}
    platform: ${{ 'iOS Simulator' }}
  run: |
    cd ios
    # ... rest of build script
- name: Test
  env:
    scheme: ${{ 'default' }}
    platform: ${{ 'iOS Simulator' }}
  run: |
    cd ios
    # ... rest of test script
